{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hcevideocall\/hcevideoview\/contentmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hcevideocall\/hcevideoview\/contentmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/contentMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"supports only .scaleAspectFill and .scaleAspectFit. default is .scaleAspectFit"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"}],"title":"contentMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HceVideoCall@objc(cs)HceVideoView(py)contentMode","modules":[{"name":"HceVideoCall"}],"navigatorTitle":[{"kind":"identifier","text":"contentMode"}]},"hierarchy":{"paths":[["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView"]]},"references":{"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView":{"role":"symbol","title":"HceVideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"}],"abstract":[{"type":"text","text":"Video View must be used display local and remote peer video."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceVideoView"}],"url":"\/documentation\/hcevideocall\/hcevideoview"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/contentMode":{"role":"symbol","title":"contentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"}],"abstract":[{"type":"text","text":"supports only .scaleAspectFill and .scaleAspectFit. default is .scaleAspectFit"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/contentMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"url":"\/documentation\/hcevideocall\/hcevideoview\/contentmode"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall":{"role":"collection","title":"HceVideoCall","abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentMode"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIViewContentMode","preciseIdentifier":"c:@E@UIViewContentMode"},{"kind":"identifier","text":"contentMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/title","value":"HceVideoView"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/fragments","value":[{"kind":"identifier","text":"HceVideoView"}]},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1contentMode\/title","value":"contentMode"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1contentMode\/fragments","value":[{"kind":"identifier","text":"contentMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}