{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hcevideocall\/hcevideoview\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hcevideocall\/hcevideoview\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/init()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@HceVideoCall@objc(cs)HceVideoView(im)init","modules":[{"name":"HceVideoCall"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView"]]},"references":{"doc://io.hce.HceVideoCall/documentation/HceVideoCall":{"role":"collection","title":"HceVideoCall","abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView":{"role":"symbol","title":"HceVideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"}],"abstract":[{"type":"text","text":"Video View must be used display local and remote peer video."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceVideoView"}],"url":"\/documentation\/hcevideocall\/hcevideoview"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hcevideocall\/hcevideoview\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/title","value":"HceVideoView"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/fragments","value":[{"kind":"identifier","text":"HceVideoView"}]},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}