{"variants":[{"paths":["\/documentation\/hcevideocall"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hcevideocall"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceDataStream","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceScreenShareExtension","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView"]},{"title":"Protocols","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCallDelegate","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCallSessionDelegate","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceDataStreamDelegate","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceScreenShareDelegate","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceScreenShareExtensionDelegate","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoProcessorType","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoViewDelegate"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"HceVideoCall","title":"HceVideoCall","symbolKind":"module","role":"collection","modules":[{"name":"HceVideoCall"}]},"hierarchy":{"paths":[[]]},"references":{"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCallSessionDelegate":{"role":"symbol","title":"HceCallSessionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceCallSessionDelegate"}],"abstract":[{"type":"text","text":"HCE video engine delegate"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCallSessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceCallSessionDelegate"}],"url":"\/documentation\/hcevideocall\/hcecallsessiondelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/RingBuffer":{"role":"symbol","title":"RingBuffer","fragments":[{"kind":"identifier","text":"RingBuffer"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RingBuffer","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/ringbuffer"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/AudioDataObserver":{"role":"symbol","title":"AudioDataObserver","fragments":[{"kind":"identifier","text":"AudioDataObserver"}],"abstract":[{"type":"text","text":"매 10ms마다 10ms만큼의 audioData를 emit한다."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AudioDataObserver","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/audiodataobserver"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/ConnectionContext":{"role":"symbol","title":"ConnectionContext","fragments":[{"kind":"identifier","text":"ConnectionContext"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/ConnectionContext","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/connectioncontext"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCallDelegate":{"role":"symbol","title":"HceCallDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceCallDelegate"}],"abstract":[{"type":"text","text":"HCE call delegate"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCallDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceCallDelegate"}],"url":"\/documentation\/hcevideocall\/hcecalldelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/AsyncOperation":{"role":"symbol","title":"AsyncOperation","fragments":[{"kind":"identifier","text":"AsyncOperation"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AsyncOperation","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/asyncoperation"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceCall":{"role":"symbol","title":"HceCall","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceCall"}],"abstract":[{"type":"text","text":"class HceCall"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceCall"}],"url":"\/documentation\/hcevideocall\/hcecall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceScreenShareDelegate":{"role":"symbol","title":"HceScreenShareDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceScreenShareDelegate"}],"abstract":[{"type":"text","text":"HceScreenShare delegate"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceScreenShareDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceScreenShareDelegate"}],"url":"\/documentation\/hcevideocall\/hcescreensharedelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoProcessorType":{"role":"symbol","title":"HceVideoProcessorType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoProcessorType"}],"abstract":[{"type":"text","text":"HCE video processor type"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoProcessorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceVideoProcessorType"}],"url":"\/documentation\/hcevideocall\/hcevideoprocessortype"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoViewDelegate":{"role":"symbol","title":"HceVideoViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoViewDelegate"}],"abstract":[{"type":"text","text":"HCE video view delegate"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceVideoViewDelegate"}],"url":"\/documentation\/hcevideocall\/hcevideoviewdelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceScreenShareExtension":{"role":"symbol","title":"HceScreenShareExtension","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceScreenShareExtension"}],"abstract":[{"type":"text","text":"Class for using the ScreenShare in Broadcast upload Extension"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceScreenShareExtension","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceScreenShareExtension"}],"url":"\/documentation\/hcevideocall\/hcescreenshareextension"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/CameraManager":{"role":"symbol","title":"CameraManager","fragments":[{"kind":"identifier","text":"CameraManager"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/CameraManager","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/cameramanager"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall":{"role":"collection","title":"HceVideoCall","abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceDataStream":{"role":"symbol","title":"HceDataStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceDataStream"}],"abstract":[{"type":"text","text":"An object that can be used to send\/receive data between call participants."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceDataStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceDataStream"}],"url":"\/documentation\/hcevideocall\/hcedatastream"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/AsyncBlockOperation":{"role":"symbol","title":"AsyncBlockOperation","fragments":[{"kind":"identifier","text":"AsyncBlockOperation"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AsyncBlockOperation","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/asyncblockoperation"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/RTCOffererDataChannelAdapter":{"role":"symbol","title":"RTCOffererDataChannelAdapter","fragments":[{"kind":"identifier","text":"RTCOffererDataChannelAdapter"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCOffererDataChannelAdapter","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/rtcoffererdatachanneladapter"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceDataStreamDelegate":{"role":"symbol","title":"HceDataStreamDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceDataStreamDelegate"}],"abstract":[{"type":"text","text":"HCE DataStream default delegate"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceDataStreamDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceDataStreamDelegate"}],"url":"\/documentation\/hcevideocall\/hcedatastreamdelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView":{"role":"symbol","title":"HceVideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"}],"abstract":[{"type":"text","text":"Video View must be used display local and remote peer video."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceVideoView"}],"url":"\/documentation\/hcevideocall\/hcevideoview"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/RTCVP8DecoderFactory":{"role":"symbol","title":"RTCVP8DecoderFactory","fragments":[{"kind":"identifier","text":"RTCVP8DecoderFactory"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCVP8DecoderFactory","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/rtcvp8decoderfactory"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceScreenShareExtensionDelegate":{"role":"symbol","title":"HceScreenShareExtensionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceScreenShareExtensionDelegate"}],"abstract":[{"type":"text","text":"HceScreenShareExtensionDelegate"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceScreenShareExtensionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceScreenShareExtensionDelegate"}],"url":"\/documentation\/hcevideocall\/hcescreenshareextensiondelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/RTCVP8EncoderFactory":{"role":"symbol","title":"RTCVP8EncoderFactory","fragments":[{"kind":"identifier","text":"RTCVP8EncoderFactory"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCVP8EncoderFactory","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/rtcvp8encoderfactory"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/RTCDataChannelAdapter":{"role":"symbol","title":"RTCDataChannelAdapter","fragments":[{"kind":"identifier","text":"RTCDataChannelAdapter"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCDataChannelAdapter","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/rtcdatachanneladapter"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/AudioManager":{"role":"symbol","title":"AudioManager","fragments":[{"kind":"identifier","text":"AudioManager"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AudioManager","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/audiomanager"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/RTCMetalView":{"role":"symbol","title":"RTCMetalView","fragments":[{"kind":"identifier","text":"RTCMetalView"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCMetalView","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/rtcmetalview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AsyncBlockOperation","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AsyncOperation","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AudioDataObserver","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/AudioManager","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/CameraManager","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/ConnectionContext","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCDataChannelAdapter","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCMetalView","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCOffererDataChannelAdapter","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCVP8DecoderFactory","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RTCVP8EncoderFactory","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/RingBuffer"]}]},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/title","value":"HceVideoView"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/fragments","value":[{"kind":"identifier","text":"HceVideoView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}