{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws NSError when error occurs while changing speaker mode"}]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Ceate this object and set as local or remote to engine using setLocalVideoView() or setRemoteVideoView()"}]},{"anchor":"example","level":2,"type":"heading","text":"example"},{"type":"codeListing","syntax":null,"code":["\/\/ creating local video view","do {","    let localVideoView = HceVideoView()","    try engine.setLocalVideoView(localVideoView)","    \/\/ add subview & set frame","} catch let exception as NSError {","    \/\/ error process","}","","\/\/ creating remote video view","do {","    let remoteUserSessionId = \"remoteUserSessionId\"","    let remoteVideoView = HceVideoView()","    try engine.setRemoteVideoView(remoteVideoView, remoteUserSessionId: remoteUserSessionId)","    \/\/ add subview & set frame","} catch let exception as NSError {","    \/\/ error process","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hcevideocall\/hcevideoview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hcevideocall\/hcevideoview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/io.hce.HceVideoCall\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/io.hce.HceVideoCall\/objc(pl)NSCoding","doc:\/\/io.hce.HceVideoCall\/objc(pl)NSObject","doc:\/\/io.hce.HceVideoCall\/objc(pl)CALayerDelegate","doc:\/\/io.hce.HceVideoCall\/s7CVarArgP","doc:\/\/io.hce.HceVideoCall\/s28CustomDebugStringConvertibleP","doc:\/\/io.hce.HceVideoCall\/s23CustomStringConvertibleP","doc:\/\/io.hce.HceVideoCall\/SQ","doc:\/\/io.hce.HceVideoCall\/SH","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIAccessibilityIdentification","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIAppearance","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIAppearanceContainer","doc:\/\/io.hce.HceVideoCall\/objc(pl)UICoordinateSpace","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIDynamicItem","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIFocusEnvironment","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIFocusItem","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIFocusItemContainer","doc:\/\/io.hce.HceVideoCall\/objc(pl)UILargeContentViewerItem","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIResponderStandardEditActions","doc:\/\/io.hce.HceVideoCall\/objc(pl)UITraitEnvironment","doc:\/\/io.hce.HceVideoCall\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video View must be used display local and remote peer video."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"}],"title":"HceVideoView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HceVideoCall@objc(cs)HceVideoView","modules":[{"name":"HceVideoCall"}],"navigatorTitle":[{"kind":"identifier","text":"HceVideoView"}]},"hierarchy":{"paths":[["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/contentMode","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/mirrorMode-swift.property"]},{"title":"Enumerations","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/MirrorMode-swift.enum"]}],"references":{"doc://io.hce.HceVideoCall/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://io.hce.HceVideoCall/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIAccessibilityIdentification"},"doc://io.hce.HceVideoCall/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIAppearance"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hcevideocall\/hcevideoview\/init()"},"doc://io.hce.HceVideoCall/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UICoordinateSpace"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/mirrorMode-swift.property":{"role":"symbol","title":"mirrorMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MirrorMode","preciseIdentifier":"s:12HceVideoCall0aB4ViewC10MirrorModeO"}],"abstract":[{"type":"text","text":"Gets\/Sets the video stream’s Mirror Mode"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/mirrorMode-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall\/hcevideoview\/mirrormode-swift.property"},"doc://io.hce.HceVideoCall/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/io.hce.HceVideoCall\/s7CVarArgP"},"doc://io.hce.HceVideoCall/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UITraitEnvironment"},"doc://io.hce.HceVideoCall/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.hce.HceVideoCall\/s28CustomDebugStringConvertibleP"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/hcevideocall\/hcevideoview\/initwithcoder:"},"doc://io.hce.HceVideoCall/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)NSObject"},"doc://io.hce.HceVideoCall/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(cs)UIView"},"doc://io.hce.HceVideoCall/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)CALayerDelegate"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/MirrorMode-swift.enum":{"role":"symbol","title":"HceVideoView.MirrorMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MirrorMode"}],"abstract":[{"type":"text","text":"Enum preset representing the MirrorMode"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/MirrorMode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MirrorMode"}],"url":"\/documentation\/hcevideocall\/hcevideoview\/mirrormode-swift.enum"},"doc://io.hce.HceVideoCall/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIFocusItemContainer"},"doc://io.hce.HceVideoCall/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIUserActivityRestoring"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView":{"role":"symbol","title":"HceVideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"}],"abstract":[{"type":"text","text":"Video View must be used display local and remote peer video."}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HceVideoView"}],"url":"\/documentation\/hcevideocall\/hcevideoview"},"doc://io.hce.HceVideoCall/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIResponderStandardEditActions"},"doc://io.hce.HceVideoCall/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIFocusEnvironment"},"doc://io.hce.HceVideoCall/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.hce.HceVideoCall\/SQ"},"doc://io.hce.HceVideoCall/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIDynamicItem"},"doc://io.hce.HceVideoCall/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.hce.HceVideoCall\/SH"},"doc://io.hce.HceVideoCall/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIAppearanceContainer"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall":{"role":"collection","title":"HceVideoCall","abstract":[],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall","kind":"symbol","type":"topic","url":"\/documentation\/hcevideocall"},"doc://io.hce.HceVideoCall/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIPasteConfigurationSupporting"},"doc://io.hce.HceVideoCall/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)NSCoding"},"doc://io.hce.HceVideoCall/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIFocusItem"},"doc://io.hce.HceVideoCall/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.hce.HceVideoCall\/s23CustomStringConvertibleP"},"doc://io.hce.HceVideoCall/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UILargeContentViewerItem"},"doc://io.hce.HceVideoCall/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/io.hce.HceVideoCall\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://io.hce.HceVideoCall/documentation/HceVideoCall/HceVideoView/contentMode":{"role":"symbol","title":"contentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"}],"abstract":[{"type":"text","text":"supports only .scaleAspectFill and .scaleAspectFit. default is .scaleAspectFit"}],"identifier":"doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/contentMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"url":"\/documentation\/hcevideocall\/hcevideoview\/contentmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HceVideoView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HceVideoView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HceVideoView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/contentMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/init()","doc:\/\/io.hce.HceVideoCall\/documentation\/HceVideoCall\/HceVideoView\/initWithCoder:"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HceVideoView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/title","value":"HceVideoView"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView\/fragments","value":[{"kind":"identifier","text":"HceVideoView"}]},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1contentMode\/title","value":"contentMode"},{"op":"replace","path":"\/references\/doc:~1~1io.hce.HceVideoCall~1documentation~1HceVideoCall~1HceVideoView~1contentMode\/fragments","value":[{"kind":"identifier","text":"contentMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}